### ISSUE TITLE
Homepage design

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/conjure-up.io-design#1]

**Comment by joanasa89** [comment]
Latest design of conjure-up.io homepage:

![conjure-up-3](https://cloud.githubusercontent.com/assets/21334617/24253914/7b681634-0fd9-11e7-8dbb-38b6f528702f.jpg)

**Comment by spencerbygraves** [comment]
@joanasa89 We've started designing code blocks/snippets on a light background, might be worth looking at for this.

https://docs.vanillaframework.io/en/patterns/code-snippet

Juju at your command section
https://jujucharms.com/

**Comment by joanasa89** [comment]
@spencerbygraves thank you!
Yes, I did use this code snippets on my first designs but we decided to go with the dark strip. 
I also think will make more sense to use the light grey background, so I will mention this on the next visual review.

**Comment by anthonydillon** [comment]
@joanasa89 is this is final could you create a PR with the final design for sign up please.

**Comment by joanasa89** [comment]
Moved to code, closed this issue.
